POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Hello World",
    "description":  "Vídeo 01",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/b7d472aa-c408-40b9-b95c-94b02f3512b0
Content-Type: application/json

{
    "title": "Hello World 3",
    "description": "Vídeo 02",
    "duration": 250
}

###

DELETE http://localhost:3333/videos/be2f467d-207e-4ab6-9517-d87ae2a75986
